CREATE TABLE IF NOT EXISTS tbl_instructor (
      ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name varchar2(500),
      last_name varchar2(500),
      email varchar2(100)
);

CREATE TABLE IF NOT EXISTS tbl_course (
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title varchar2(500),
        description varchar2(500),
        instructor_id INTEGER,
        foreign key (instructor_id) references tbl_instructor(id)
);


ALTER TABLE
    tbl_course
    ADD CONSTRAINT title_UNIQUE
        UNIQUE ( title );


CREATE TABLE IF NOT EXISTS tbl_review (
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        comment varchar2(500),
        course_id INTEGER,
        foreign key (course_id) references tbl_course(id)
);


CREATE TABLE IF NOT EXISTS tbl_student (
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        first_name varchar2(500),
        last_name varchar2(500),
        email varchar2(100)
);

CREATE TABLE IF NOT EXISTS tbl_course_student (
    course_id BIGINT,
    student_id BIGINT,
    primary key(course_id,student_id),
    foreign key (course_id) references tbl_course(id),
    foreign key (student_id) references tbl_student(id)
)
